import json
import re
import requests

from learning.models import Subject, Topic
from quizzes.models import Question


class QuizGenerator:

    @staticmethod
    def get_subject_content(subject_id):
        """
        Fetch all topic content for a subject and combine it into one string.
        """

        topics = Topic.objects.filter(
            unit__subject_id=subject_id
        ).order_by("unit__order", "order", "id")

        content = ""

        for topic in topics:
            content += f"\n\nTopic: {topic.title}\n"
            content += topic.markdown_content

        return content

    @staticmethod
    def clean_text(value, max_length=None):
        """
        Clean text before saving into database.
        """

        text = str(value).strip()

        if max_length is not None and len(text) > max_length:
            text = text[:max_length]

        return text

    @staticmethod
    def normalize_correct_answer(answer):
        """
        Convert correct answer into A, B, C, or D.
        """

        answer = str(answer).strip().upper()

        if answer in ["A", "B", "C", "D"]:
            return answer

        if answer.startswith("A"):
            return "A"

        if answer.startswith("B"):
            return "B"

        if answer.startswith("C"):
            return "C"

        if answer.startswith("D"):
            return "D"

        return ""

    @staticmethod
    def build_prompt(content, level, num_questions=1, topic_title=""):
        """
        Build a strict prompt for Qwen.
        """

        topic_name = topic_title if topic_title else "Topic name"

        prompt = f"""
You are an educational quiz generator.

Generate exactly {num_questions} multiple choice questions from the content below.

Topic: {topic_name}

Difficulty Level: {level}

Strict Rules:
- Each question must have exactly 4 options.
- Options must be named option_a, option_b, option_c, option_d.
- correct_answer must be only one letter: A, B, C, or D.
- Questions must be based only on the provided content.
- Do not add markdown formatting.
- Do not wrap output in ```json.
- Return only valid JSON.
- The JSON must be a list.
- Do not write any explanation outside JSON.

Required JSON format:
[
  {{
    "topic": "{topic_name}",
    "question_text": "Question text",
    "option_a": "First option",
    "option_b": "Second option",
    "option_c": "Third option",
    "option_d": "Fourth option",
    "correct_answer": "A"
  }}
]

Content:
{content}
"""

        return prompt

    @staticmethod
    def generate_questions_with_ollama(prompt):
        """
        Send prompt to Ollama Qwen model and return generated response.
        """

        url = "http://localhost:11434/api/generate"

        payload = {
            "model": "qwen2.5:1.5b",
            "prompt": prompt,
            "stream": False
        }

        response = requests.post(
            url,
            json=payload,
            timeout=180
        )

        if response.status_code != 200:
            raise Exception("Ollama request failed")

        data = response.json()

        return data.get("response", "")

    @staticmethod
    def parse_questions(response_text):
        """
        Convert Qwen text response into Python list.
        """

        cleaned_text = response_text.strip()

        if cleaned_text == "":
            raise Exception("LLM returned empty response. Try reducing content size.")

        cleaned_text = re.sub(
            r"^```json",
            "",
            cleaned_text
        ).strip()

        cleaned_text = re.sub(
            r"^```",
            "",
            cleaned_text
        ).strip()

        cleaned_text = re.sub(
            r"```$",
            "",
            cleaned_text
        ).strip()

        start_index = cleaned_text.find("[")
        end_index = cleaned_text.rfind("]")

        if start_index == -1 or end_index == -1:
            raise Exception(
                f"LLM did not return a JSON list. Response was:\n{cleaned_text}"
            )

        cleaned_text = cleaned_text[start_index:end_index + 1]

        try:
            questions = json.loads(cleaned_text)
        except json.JSONDecodeError as error:
            raise Exception(
                f"Invalid JSON generated by LLM: {error}\nResponse was:\n{cleaned_text}"
            )

        if isinstance(questions, dict) and "questions" in questions:
            questions = questions["questions"]

        if not isinstance(questions, list):
            raise Exception("LLM response must be a JSON list.")

        return questions

    @staticmethod
    def get_level_offset(level, total_topics):
        """
        Rotate topic priority based on level.
        This helps different levels cover different topics fairly.
        """

        level_positions = {
            "basic": 0,
            "moderate": 1,
            "difficult": 2
        }

        level_index = level_positions.get(level, 0)

        if total_topics == 0:
            return 0

        offset = level_index * max(1, total_topics // 3)

        return offset % total_topics

    @staticmethod
    def select_evenly_from_topics(topics, total_questions, level):
        """
        If topics are more than total questions,
        select topics evenly from the full topic list.
        """

        topics = list(topics)
        total_topics = len(topics)

        if total_topics <= total_questions:
            return topics

        offset = QuizGenerator.get_level_offset(level, total_topics)

        rotated_topics = topics[offset:] + topics[:offset]

        selected_topics = []

        if total_questions == 1:
            selected_topics.append(rotated_topics[0])
            return selected_topics

        for index in range(total_questions):
            topic_index = round(index * (total_topics - 1) / (total_questions - 1))
            selected_topics.append(rotated_topics[topic_index])

        return selected_topics

    @staticmethod
    def calculate_question_distribution(topics, total_questions, level):
        """
        Distribute total questions equally among topics.
        """

        topics = list(topics)
        total_topics = len(topics)

        if total_topics == 0:
            raise Exception("No topics found for this subject.")

        if total_questions <= 0:
            raise Exception("Total questions must be greater than 0.")

        if total_topics > total_questions:
            selected_topics = QuizGenerator.select_evenly_from_topics(
                topics,
                total_questions,
                level
            )

            distribution = []

            for topic in selected_topics:
                distribution.append((topic, 1))

            return distribution

        base_questions = total_questions // total_topics
        extra_questions = total_questions % total_topics

        offset = QuizGenerator.get_level_offset(level, total_topics)

        rotated_topics = topics[offset:] + topics[:offset]

        question_count_map = {}

        for index, topic in enumerate(rotated_topics):
            question_count = base_questions

            if index < extra_questions:
                question_count += 1

            question_count_map[topic.id] = question_count

        distribution = []

        for topic in topics:
            distribution.append((topic, question_count_map[topic.id]))

        return distribution

    @staticmethod
    def save_questions_for_topic(subject, topic, level, questions, limit=None):
        """
        Save parsed LLM questions into the Question table using the known topic.
        """

        saved_questions = []

        for item in questions:
            if limit is not None and len(saved_questions) >= limit:
                break

            if not isinstance(item, dict):
                print("Skipped question. Invalid item format.")
                continue

            question_text = QuizGenerator.clean_text(
                item.get("question_text", "")
            )

            option_a = QuizGenerator.clean_text(
                item.get("option_a", ""),
                max_length=255
            )

            option_b = QuizGenerator.clean_text(
                item.get("option_b", ""),
                max_length=255
            )

            option_c = QuizGenerator.clean_text(
                item.get("option_c", ""),
                max_length=255
            )

            option_d = QuizGenerator.clean_text(
                item.get("option_d", ""),
                max_length=255
            )

            correct_answer = QuizGenerator.normalize_correct_answer(
                item.get("correct_answer", "")
            )

            if question_text == "":
                print("Skipped question. Empty question text.")
                continue

            if option_a == "" or option_b == "" or option_c == "" or option_d == "":
                print("Skipped question. One or more options are empty.")
                continue

            if correct_answer not in ["A", "B", "C", "D"]:
                print("Skipped question. Invalid correct answer.")
                continue

            question = Question.objects.create(
                subject=subject,
                topic=topic,
                level=level,
                question_text=question_text,
                option_a=option_a,
                option_b=option_b,
                option_c=option_c,
                option_d=option_d,
                correct_answer=correct_answer
            )

            saved_questions.append(question)

        return saved_questions

    @staticmethod
    def generate_and_save_questions_for_topic(topic, level, num_questions):
        """
        Generate and save questions for one specific topic.
        """

        subject = topic.unit.subject

        content = f"""
Topic: {topic.title}

{topic.markdown_content}
"""

        limited_content = content[:3000]

        prompt = QuizGenerator.build_prompt(
            limited_content,
            level,
            num_questions=num_questions,
            topic_title=topic.title
        )

        response = QuizGenerator.generate_questions_with_ollama(prompt)

        questions = QuizGenerator.parse_questions(response)

        saved_questions = QuizGenerator.save_questions_for_topic(
            subject=subject,
            topic=topic,
            level=level,
            questions=questions,
            limit=num_questions
        )

        return {
            "topic_id": topic.id,
            "topic_title": topic.title,
            "requested": num_questions,
            "generated": len(questions),
            "saved": len(saved_questions)
        }

    @staticmethod
    def generate_standard_quiz_for_subject(
        subject_id,
        level,
        total_questions=15,
        replace_existing=True
    ):
        """
        Generate standard permanent quiz questions for one subject and one level.

        Example:
        subject_id = 1
        level = basic
        total_questions = 15
        """

        valid_levels = ["basic", "moderate", "difficult"]

        if level not in valid_levels:
            raise Exception("Invalid level. Use basic, moderate, or difficult.")

        subject = Subject.objects.get(id=subject_id)

        topics = Topic.objects.filter(
            unit__subject=subject
        ).order_by("unit__order", "order", "id")

        distribution = QuizGenerator.calculate_question_distribution(
            topics,
            total_questions,
            level
        )

        if replace_existing:
            deleted_count, deleted_details = Question.objects.filter(
                subject=subject,
                level=level
            ).delete()

            print(f"Deleted old {level} questions:", deleted_count)

        total_saved = 0
        details = []

        for topic, question_count in distribution:
            print(f"Generating {question_count} question(s) for topic: {topic.title}")

            try:
                result = QuizGenerator.generate_and_save_questions_for_topic(
                    topic=topic,
                    level=level,
                    num_questions=question_count
                )

                total_saved += result["saved"]
                details.append(result)

                print(f"Saved {result['saved']} question(s) for topic: {topic.title}")

            except Exception as error:
                error_details = {
                    "topic_id": topic.id,
                    "topic_title": topic.title,
                    "requested": question_count,
                    "generated": 0,
                    "saved": 0,
                    "error": str(error)
                }

                details.append(error_details)

                print(f"Failed for topic: {topic.title}")
                print(error)

        return {
            "subject": subject.name,
            "level": level,
            "total_requested": total_questions,
            "total_saved": total_saved,
            "topics_used": len(distribution),
            "details": details
        }

    @staticmethod
    def generate_and_save_standard_quiz(subject_id, level, num_questions=15):
        """
        Old method name kept for testing.
        It now uses the new balanced standard quiz logic.
        """

        return QuizGenerator.generate_standard_quiz_for_subject(
            subject_id=subject_id,
            level=level,
            total_questions=num_questions,
            replace_existing=True
        )